command: ['streamlit', 'run', 'Dashboard_Main.py']

env:
  - name: DBX_SQL_WAREHOUSE
    valueFrom: sql-warehouse
  - name: REGIONS_TABLE
    valueFrom: regions
  - name: REGION_MANAGERS_TABLE
    valueFrom: region_managers
  - name: REGION_TYPES_TABLE
    valueFrom: region_types
  - name: LAND_USE_TYPES_TABLE
    valueFrom: land_use_types
  - name: LAND_USAGE_TABLE
    valueFrom: land_usage
  - name: CLIMATE_MARKERS_TABLE
    valueFrom: climate_markers
